### ISSUE TITLE
Choose an open source license

### ISSUE THREAD

**Issue by Genestealer** [Dullage/SwitchedRelay#1]
I love you code and wish to integrate some of it into my own [https://github.com/Genestealer](https://github.com/Genestealer).

May I ask which [Open source license](https://choosealicense.com/) are you happy with, which you can assign to your code. Instructions: https://github.com/blog/1530-choosing-an-open-source-license

**Comment by Dullage** [comment]
Hi Genestealer. Happy to hear it may be of some use. I've added an MIT license to the repo.
